### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by marl64** [marl64/gbcam-border#1]
- [ ] file select dialog for individual image
 - [ ] folder select dialog for batch processing
 - [ ] preview image in GUI - updates immediately
 - [ ] drop-down list of borders
 - [ ] drop-down list of scaling options 1-5
 - [ ] append filename with specific border name, save to source folder
 - [ ] colour palettes based on GBC palettes?
